### ISSUE TITLE
no module named "classification_helper"

### ISSUE THREAD

**Issue by calvin272m** [pedvide/ISLR_Python#1]
when I tried to do the code line 'from classification_helper import print_classification_statistics, plot_ROC, plot_OLS_error_table, plot_classification"

it gives me error message:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-84-11e177a96c71> in <module>
     16 from itertools import groupby
     17 import warnings
---> 18 from classification_helper import print_classification_statistics, plot_ROC, print_OLS_error_table, plot_classification
     19 get_ipython().run_line_magic('matplotlib', 'inline')
     20 plt.style.use('seaborn-white')

ModuleNotFoundError: No module named 'classification_helper'
I tried to search any reference online to fix, it seems like the code comes from nowhere. 
hope someone could help me fix this. thanks

**Comment by pedvide** [comment]
Hey, sorry for the long long delay. `classification_helper.py` is one of the files in this repository, I think you forgot to download it.
